use yt-dlp patched ffmpeg, add phantomjs for yt-dlp

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -31,7 +31,8 @@ cd ffmpeg
 
 if [[ -z $FFMPEG_DOWNLOAD_URL ]]; then
   echo "Variable FFMPEG_DOWNLOAD_URL isn't set, using default value" | output
-  FFMPEG_DOWNLOAD_URL="https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
+  #FFMPEG_DOWNLOAD_URL="https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
+  FFMPEG_DOWNLOAD_URL="https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
 fi
 
 echo "Downloading $FFMPEG_DOWNLOAD_URL" | output
@@ -44,13 +45,29 @@ fi
 
 echo "Unpacking the archive" | output
 
-tar xJf "./$FFMPEG_ARCHIVE_NAME" --strip-components=1
+tar xJf "./$FFMPEG_ARCHIVE_NAME" --strip-components=2 ffmpeg-master-latest-linux64-gpl/bin
 
 if [ "$?" != "0" ]; then
   echo "Failed to unpack" | output && exit 1
 fi
 
 rm $FFMPEG_ARCHIVE_NAME
+
+#########################
+PHANTOMJS_ARCHIVE_NAME="phantomjs.tar.bz2"
+PHANTOMJS_DOWNLOAD_URL=https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
+echo "Downloading $PHANTOMJS_DOWNLOAD_URL" | output
+code=$(curl "$PHANTOMJS_DOWNLOAD_URL" -L --silent --fail --retry 5 --retry-max-time 15 -o ./$PHANTOMJS_ARCHIVE_NAME --write-out "%{http_code}")
+if [ "$code" != "200" ]; then
+  echo "Unable to download PhantomJS: $code" | output && exit 1
+fi
+echo "Unpacking the archive" | output
+tar xf "./$PHANTOMJS_ARCHIVE_NAME" --strip-components=2 phantomjs-2.1.1-linux-x86_64/bin
+if [ "$?" != "0" ]; then
+  echo "Failed to unpack" | output && exit 1
+fi
+rm $PHANTOMJS_ARCHIVE_NAME
+#########################
 
 PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
 mkdir -p $(dirname $PROFILE_PATH)
